### PR TITLE
Greatly Decreased Memory Usage

### PR DESCRIPTION
**Pull request by alexjweil**
First off, I love that you built this! I saw your [post on /r/Ruby](https://www.reddit.com/r/ruby/comments/3bm76o/), and, as a fan of both German and Ruby, I had to take a peek. Allen Respekt! :smiley:

Now for the actual meat of things; there are two minor bugs that I came across, so I've included their fixes here.
1. On computers where the default encoding is ASCII (and, I'd guess, any other encoding that doesn't support umlauts), importing a dictionary containing letters with umlauts causes the error: `stimmung.rb:19:in `split': invalid byte sequence in US-ASCII (ArgumentError)`
   
   Luckily, though, the fix is pretty easy: a simple `#<Encoding:UTF-8>` at the top of the file fixed things right up for me. That fix is commit 75efc59d4737838cd5cf6cb103bceeac675be6d3.
2. The regex that was being used to split words in Stimmung#score was `/[\s\!\?]+/`, but that misses out on a few important characters, like semi-colons, periods, and tab characters, which means that sentences like "Ich; liebe; Semikolons;." don't get the right scores. I replaced that regex with `/\W+/`, which matches one or more non-word characters. That's commit bd301a5d210ca6053ec484c535f7fbc924ddaae4

Finally, the biggest changes I've made were to decrease the program's memory usage by performing operations in place, when possible, to limit the amount of unnecessary copying, and reading more efficiently from the dictionaries. And, of course, all the tests still pass.

To prove that there's actually an improvement from these changes, I used the following benchmark:

``` ruby
require 'memory_profiler'
report = MemoryProfiler.report do
  stimmung = Stimmung.new
  print stimmung.score('Was macht ein Hacker am See? Phishen!')
end
report.pretty_print
```

With the original code, this gave the (shortened) output:

```
Total allocated: 19633200 bytes (250401 objects)

allocated memory by location
-----------------------------------
  15128669  stimmung/lib/stimmung.rb:25
   1708742  stimmung/lib/stimmung.rb:24
   1553720  stimmung/lib/stimmung.rb:10
   1240080  stimmung/lib/stimmung.rb:26
      ...

allocated memory by class
-----------------------------------
   8774640  MatchData
   7730601  String
   1557080  Array
   1553720  Hash
     16864  File
        40  Stimmung
```

After switching to `File#foreach` to read the strings in the dictionary and then calling `#freeze` on those strings, we see a huge improvement - 58.9% less allocated memory:

```
Total allocated: 8063173 bytes (156758 objects)

allocated memory by location
-----------------------------------
   5102260  stimmung/lib/stimmung.rb:24
   1553720  stimmung/lib/stimmung.rb:11
   1405542  stimmung/lib/stimmung.rb:23
      ...

allocated memory by class
-----------------------------------
   5238349  String
   1553720  Hash
   1253920  Array
     16864  File
       280  MatchData
        40  Stimmung
```

But we can do better. Changing `line.chomp.split` to `line.chomp!.split` in `#load_dictionary` gives us a ~66% decrease in memory usage versus the original:

```
Total allocated: 6723362 bytes (125424 objects)

allocated memory by location
-----------------------------------
   3763383  stimmung/lib/stimmung.rb:24
   1553720  stimmung/lib/stimmung.rb:11
   1404199  stimmung/lib/stimmung.rb:23
       ....

allocated memory by class
-----------------------------------
   3898130  String
   1553952  Hash
   1253920  Array
     16864  File
       280  MatchData
       176  Mutex
        40  Stimmung
```

Using the following test, we can also see that the new code runs faster:

``` ruby
require 'ruby-prof'
result = RubyProf.profile do
  500.times {Stimmung.new}
end
```

The test yields a runtime of `6.803990s` for the original code, and `3.699070s` for the modified code. Not bad for roughly three lines of code. :smile:

Anyhow, great job with this, and I hope this contribution's useful - let me know if you've got any questions or requests. Mach weiter so!

### CODE REVIEW

**Comment by pachacamac** [comment]
Hey Alex,

Wow thank you for your contribution! This is awesome and very likely the most elaborate pull request I received on GitHub so far  :)

I just have one small remark regarding commit `bd301a5`: Simply splitting by `/\W+/` won't do the trick here since then none of the emoticons (see lib/emoticons.txt) would be recognized later on. If you have a better solution for this, feel free to change this commit, otherwise could you please change your pull request so it doesn't include commit `bd301a5` and `42902a6`?

Super vielen lieben Dank!!

**Comment by alexjweil** [comment]
Thanks! Ich bin froh, das zu hören! As for the the regex thing, you're absolutely right - I can't believe I forgot about the emoticons. My first thought is that it may be too hard to accomplish it with just one pass - maybe the best approach is to first extract all emoticons from the string, then split it? I'll look into that, and, if I can't get something figured out, I'll change things back.

**Comment by pachacamac** [comment]
Maybe [this](http://stackoverflow.com/questions/5862490/how-to-match-emoticons-with-regular-expressions) could be an inspiration.

**Comment by alexjweil** [comment]
I think I've gotten the regex to play nicely by taking advantage of the fact that no word in your dictionary is shorter than three letters (Hurra für vielsilbige Wörter! :smile:), by defining punctuation as "exactly one special character preceded by three or more word characters and followed by whitespace or the end of the line," and then removing anything that matches and splitting on whitespace or a word boundary followed by a non-word character. (It's an annoying pair of regexes - see e5ae6a42a2aececbe6c42dd4075cc81a591add02 ) 

I'm sure there's a better or more elegant way to accomplish this, and in situations like `gut!:)` there's probably nothing we can do, but I think this handles the great majority of cases pretty well.

Also, I noticed that my previous solution for the UTF-8 issue wasn't thorough enough, so I solved that problem by adding another explicit UTF-8 declaration in a888fbfc1140ffb0e739435e8c213025d871e5ee.

Next, I realized that the emoticon `:P` was listed twice in the dictionary, so I removed the second one and fixed the test in 215c572a4c1222d14dfe73cb88ab53310509f9e7 and d9e4f5ca68318ed22e4bd4ac6730a3727bad1141.

On the subject of tests, I just noticed a bug. Right now, in `#score`, we're calling `str.downcase` before splitting, meaning that it's impossible for something like `:D` to ever match the dictionary, because it'll just get converted to `:d`.

For the moment, my solution is to make the whole emoticons dictionary lowercase too, but that runs into problems with emoticons like `D:` and `d:`, which mean very different things. Right now, that situation's just a hypothetical, as there aren't any such conflicts in the dictionary you're using, but it's something to think about.

**Comment by pachacamac** [comment]
Cool solution, I like it! Emoticons are definitely hard to handle and I don't think it's something that is usually done in most sentiment analysis tools. I adopted the idea (and dictionary) from [sentimental](https://github.com/7compass/sentimental/blob/master/lib/sentislang.txt) but haven't seen it in other libs so far.

Shame that Ruby, and many other languages, still have so many problems with UTF8 support by default and I'm glad you noticed- and fixed it :)

Btw what is your incentive in Stimmung? Are you using it for something cool? :)

**Comment by alexjweil** [comment]
I'm glad you like it! Hopefully, as time goes on, we'll see more people using Unicode emoticons, like :smile:, 'cause those are a lot easier to deal with!

It still blows my mind that everything isn't just UTF8 by default, too. I know there are some special situations where single-byte encodings are better, but I feel like this is one of those situations where [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) is the way to go.

As for Stimmung, I don't really have an exciting reason for being a part, other than seeing your post and thinking it looked cool. One of my big interests is combining technology with language, and I'm a huge fan of German and Ruby in particular, so this project is, well, [supergeil](https://youtu.be/jxVcgDMBU94?t=53) :wink:. If I do come up with some clever idea, I'll make sure to keep you posted.

**Pull request merged**
